Update assemble

diff --git a/.s2i/bin/assemble b/.s2i/bin/assemble
--- a/.s2i/bin/assemble
+++ b/.s2i/bin/assemble
@@ -120,6 +120,57 @@ if [ -d $LOCAL_SOURCE_DIR/configuration ]; then
   cp -v $LOCAL_SOURCE_DIR/configuration/* $JBOSS_HOME/standalone/configuration/
 fi
 
+
+configure_proxy
+configure_mirrors
+
+manage_incremental_build
+
+# If a pom.xml is present, this is a normal build scenario
+# so run maven.
+if [ -f "$LOCAL_SOURCE_DIR/pom.xml" ]; then
+  pushd $LOCAL_SOURCE_DIR &> /dev/null
+
+  MAVEN_ARGS=${MAVEN_ARGS--e -Popenshift -DskipTests -Dcom.redhat.xpaas.repo.redhatga package}
+
+  # Always force IPv4 (CLOUD-188)
+  # Append user-supplied arguments (CLOUD-412)
+  MAVEN_ARGS="$MAVEN_ARGS -Djava.net.preferIPv4Stack=true ${MAVEN_ARGS_APPEND}"
+
+  echo "Found pom.xml... attempting to build with 'mvn ${MAVEN_ARGS}'"
+
+  echo "Using $(mvn --version)"
+
+  # Execute the actual build
+  mvn $MAVEN_ARGS
+
+  ERR=$?
+  if [ $ERR -ne 0 ]; then
+    echo "Aborting due to error code $ERR from Maven build"
+    exit $ERR
+  fi
+  
+   # Copy built artifacts (if any!) from the target/ directory
+  # (or $ARTIFACT_DIR if specified)
+  # to the $JBOSS_HOME/standalone/deployments/ directory for
+  # later deployment
+  copy_artifacts "$ARTIFACT_DIR" war ear rar jar
+
+  # copy app data, if specified
+  if [ -n "${APP_DATADIR+_}" ] && [ -d "$LOCAL_SOURCE_DIR/$APP_DATADIR" ]; then
+    echo "Copying app data to $DATA_DIR..."
+    src="$LOCAL_SOURCE_DIR/$APP_DATADIR"
+    [ -d "$DATA_DIR" ] && src="$src/*" # avoid glob if possible
+    cp -av "$src" "$DATA_DIR"
+  fi
+
+  # optionally clear the local maven repository after the build
+  clear_maven_repository
+
+  popd &> /dev/null
+else
+  copy_artifacts "." war ear rar jar
+fi
   
 # Copy (probably binary) artifacts from the deployments/
 # directory to the $JBOSS_HOME/standalone/deployments/
